[package]
name = "VideoReencodingNetClient"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json", "multipart"] }
tokio = { version = "1.34", features = ["full"] }
shellexpand = "3.1.1"
clap = { version = "4.5.37", features = ["derive"] }